var a =
{
    url: 'https://api.github.com/repos/HippoCMMS/LoginSite/pulls/10',
    id: 220913528,
    node_id: 'MDExOlB1bGxSZXF1ZXN0MjIwOTEzNTI4',
    html_url: 'https://github.com/HippoCMMS/LoginSite/pull/10',
    diff_url: 'https://github.com/HippoCMMS/LoginSite/pull/10.diff',
    patch_url: 'https://github.com/HippoCMMS/LoginSite/pull/10.patch',
    issue_url: 'https://api.github.com/repos/HippoCMMS/LoginSite/issues/10',
    number: 10,
    state: 'open',
    locked: false,
    title: 'bot test',
    user:
    {
        login: 'felipenvaz',
        id: 20460244,
        node_id: 'MDQ6VXNlcjIwNDYwMjQ0',
        avatar_url: 'https://avatars0.githubusercontent.com/u/20460244?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/felipenvaz',
        html_url: 'https://github.com/felipenvaz',
        followers_url: 'https://api.github.com/users/felipenvaz/followers',
        following_url: 'https://api.github.com/users/felipenvaz/following{/other_user}',
        gists_url: 'https://api.github.com/users/felipenvaz/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/felipenvaz/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/felipenvaz/subscriptions',
        organizations_url: 'https://api.github.com/users/felipenvaz/orgs',
        repos_url: 'https://api.github.com/users/felipenvaz/repos',
        events_url: 'https://api.github.com/users/felipenvaz/events{/privacy}',
        received_events_url: 'https://api.github.com/users/felipenvaz/received_events',
        type: 'User',
        site_admin: false
    },
    body: null,
    created_at: '2018-10-06T21:49:06Z',
    updated_at: '2018-10-06T21:49:06Z',
    closed_at: null,
    merged_at: null,
    merge_commit_sha: '38f952d46c87843fb786a271ad16346fff746e07',
    assignee: null,
    assignees: [],
    requested_reviewers: [],
    requested_teams: [],
    labels: [],
    milestone: null,
    commits_url: 'https://api.github.com/repos/HippoCMMS/LoginSite/pulls/10/commits',
    review_comments_url: 'https://api.github.com/repos/HippoCMMS/LoginSite/pulls/10/comments',
    review_comment_url: 'https://api.github.com/repos/HippoCMMS/LoginSite/pulls/comments{/number}',
    comments_url: 'https://api.github.com/repos/HippoCMMS/LoginSite/issues/10/comments',
    statuses_url: 'https://api.github.com/repos/HippoCMMS/LoginSite/statuses/5d3954c86ff2fe10efe769ad7f33a2724228f6d4',
    head:
    {
        label: 'HippoCMMS:test/breaking',
        ref: 'test/breaking',
        sha: '5d3954c86ff2fe10efe769ad7f33a2724228f6d4',
        user:
        {
            login: 'HippoCMMS',
            id: 43096998,
            node_id: 'MDEyOk9yZ2FuaXphdGlvbjQzMDk2OTk4',
            avatar_url: 'https://avatars0.githubusercontent.com/u/43096998?v=4',
            gravatar_id: '',
            url: 'https://api.github.com/users/HippoCMMS',
            html_url: 'https://github.com/HippoCMMS',
            followers_url: 'https://api.github.com/users/HippoCMMS/followers',
            following_url: 'https://api.github.com/users/HippoCMMS/following{/other_user}',
            gists_url: 'https://api.github.com/users/HippoCMMS/gists{/gist_id}',
            starred_url: 'https://api.github.com/users/HippoCMMS/starred{/owner}{/repo}',
            subscriptions_url: 'https://api.github.com/users/HippoCMMS/subscriptions',
            organizations_url: 'https://api.github.com/users/HippoCMMS/orgs',
            repos_url: 'https://api.github.com/users/HippoCMMS/repos',
            events_url: 'https://api.github.com/users/HippoCMMS/events{/privacy}',
            received_events_url: 'https://api.github.com/users/HippoCMMS/received_events',
            type: 'Organization',
            site_admin: false
        },
        repo:
        {
            id: 148803066,
            node_id: 'MDEwOlJlcG9zaXRvcnkxNDg4MDMwNjY=',
            name: 'LoginSite',
            full_name: 'HippoCMMS/LoginSite',
            private: true,
            owner: [Object],
            html_url: 'https://github.com/HippoCMMS/LoginSite',
            description: null,
            fork: false,
            url: 'https://api.github.com/repos/HippoCMMS/LoginSite',
            forks_url: 'https://api.github.com/repos/HippoCMMS/LoginSite/forks',
            keys_url: 'https://api.github.com/repos/HippoCMMS/LoginSite/keys{/key_id}',
            collaborators_url: 'https://api.github.com/repos/HippoCMMS/LoginSite/collaborators{/collaborator}',
            teams_url: 'https://api.github.com/repos/HippoCMMS/LoginSite/teams',
            hooks_url: 'https://api.github.com/repos/HippoCMMS/LoginSite/hooks',
            issue_events_url: 'https://api.github.com/repos/HippoCMMS/LoginSite/issues/events{/number}',
            events_url: 'https://api.github.com/repos/HippoCMMS/LoginSite/events',
            assignees_url: 'https://api.github.com/repos/HippoCMMS/LoginSite/assignees{/user}',
            branches_url: 'https://api.github.com/repos/HippoCMMS/LoginSite/branches{/branch}',
            tags_url: 'https://api.github.com/repos/HippoCMMS/LoginSite/tags',
            blobs_url: 'https://api.github.com/repos/HippoCMMS/LoginSite/git/blobs{/sha}',
            git_tags_url: 'https://api.github.com/repos/HippoCMMS/LoginSite/git/tags{/sha}',
            git_refs_url: 'https://api.github.com/repos/HippoCMMS/LoginSite/git/refs{/sha}',
            trees_url: 'https://api.github.com/repos/HippoCMMS/LoginSite/git/trees{/sha}',
            statuses_url: 'https://api.github.com/repos/HippoCMMS/LoginSite/statuses/{sha}',
            languages_url: 'https://api.github.com/repos/HippoCMMS/LoginSite/languages',
            stargazers_url: 'https://api.github.com/repos/HippoCMMS/LoginSite/stargazers',
            contributors_url: 'https://api.github.com/repos/HippoCMMS/LoginSite/contributors',
            subscribers_url: 'https://api.github.com/repos/HippoCMMS/LoginSite/subscribers',
            subscription_url: 'https://api.github.com/repos/HippoCMMS/LoginSite/subscription',
            commits_url: 'https://api.github.com/repos/HippoCMMS/LoginSite/commits{/sha}',
            git_commits_url: 'https://api.github.com/repos/HippoCMMS/LoginSite/git/commits{/sha}',
            comments_url: 'https://api.github.com/repos/HippoCMMS/LoginSite/comments{/number}',
            issue_comment_url: 'https://api.github.com/repos/HippoCMMS/LoginSite/issues/comments{/number}',
            contents_url: 'https://api.github.com/repos/HippoCMMS/LoginSite/contents/{+path}',
            compare_url: 'https://api.github.com/repos/HippoCMMS/LoginSite/compare/{base}...{head}',
            merges_url: 'https://api.github.com/repos/HippoCMMS/LoginSite/merges',
            archive_url: 'https://api.github.com/repos/HippoCMMS/LoginSite/{archive_format}{/ref}',
            downloads_url: 'https://api.github.com/repos/HippoCMMS/LoginSite/downloads',
            issues_url: 'https://api.github.com/repos/HippoCMMS/LoginSite/issues{/number}',
            pulls_url: 'https://api.github.com/repos/HippoCMMS/LoginSite/pulls{/number}',
            milestones_url: 'https://api.github.com/repos/HippoCMMS/LoginSite/milestones{/number}',
            notifications_url: 'https://api.github.com/repos/HippoCMMS/LoginSite/notifications{?since,all,participating}',
            labels_url: 'https://api.github.com/repos/HippoCMMS/LoginSite/labels{/name}',
            releases_url: 'https://api.github.com/repos/HippoCMMS/LoginSite/releases{/id}',
            deployments_url: 'https://api.github.com/repos/HippoCMMS/LoginSite/deployments',
            created_at: '2018-09-14T14:52:26Z',
            updated_at: '2018-10-05T20:21:54Z',
            pushed_at: '2018-10-06T21:56:36Z',
            git_url: 'git://github.com/HippoCMMS/LoginSite.git',
            ssh_url: 'git@github.com:HippoCMMS/LoginSite.git',
            clone_url: 'https://github.com/HippoCMMS/LoginSite.git',
            svn_url: 'https://github.com/HippoCMMS/LoginSite',
            homepage: null,
            size: 709,
            stargazers_count: 0,
            watchers_count: 0,
            language: 'JavaScript',
            has_issues: true,
            has_projects: true,
            has_downloads: true,
            has_wiki: true,
            has_pages: false,
            forks_count: 0,
            mirror_url: null,
            archived: false,
            open_issues_count: 2,
            license: null,
            forks: 0,
            open_issues: 2,
            watchers: 0,
            default_branch: 'master'
        }
    },
    base:
    {
        label: 'HippoCMMS:release',
        ref: 'release',
        sha: 'b35a8717fb64f4a5f7bc711186801f9b62963a31',
        user:
        {
            login: 'HippoCMMS',
            id: 43096998,
            node_id: 'MDEyOk9yZ2FuaXphdGlvbjQzMDk2OTk4',
            avatar_url: 'https://avatars0.githubusercontent.com/u/43096998?v=4',
            gravatar_id: '',
            url: 'https://api.github.com/users/HippoCMMS',
            html_url: 'https://github.com/HippoCMMS',
            followers_url: 'https://api.github.com/users/HippoCMMS/followers',
            following_url: 'https://api.github.com/users/HippoCMMS/following{/other_user}',
            gists_url: 'https://api.github.com/users/HippoCMMS/gists{/gist_id}',
            starred_url: 'https://api.github.com/users/HippoCMMS/starred{/owner}{/repo}',
            subscriptions_url: 'https://api.github.com/users/HippoCMMS/subscriptions',
            organizations_url: 'https://api.github.com/users/HippoCMMS/orgs',
            repos_url: 'https://api.github.com/users/HippoCMMS/repos',
            events_url: 'https://api.github.com/users/HippoCMMS/events{/privacy}',
            received_events_url: 'https://api.github.com/users/HippoCMMS/received_events',
            type: 'Organization',
            site_admin: false
        },
        repo:
        {
            id: 148803066,
            node_id: 'MDEwOlJlcG9zaXRvcnkxNDg4MDMwNjY=',
            name: 'LoginSite',
            full_name: 'HippoCMMS/LoginSite',
            private: true,
            owner: [Object],
            html_url: 'https://github.com/HippoCMMS/LoginSite',
            description: null,
            fork: false,
            url: 'https://api.github.com/repos/HippoCMMS/LoginSite',
            forks_url: 'https://api.github.com/repos/HippoCMMS/LoginSite/forks',
            keys_url: 'https://api.github.com/repos/HippoCMMS/LoginSite/keys{/key_id}',
            collaborators_url: 'https://api.github.com/repos/HippoCMMS/LoginSite/collaborators{/collaborator}',
            teams_url: 'https://api.github.com/repos/HippoCMMS/LoginSite/teams',
            hooks_url: 'https://api.github.com/repos/HippoCMMS/LoginSite/hooks',
            issue_events_url: 'https://api.github.com/repos/HippoCMMS/LoginSite/issues/events{/number}',
            events_url: 'https://api.github.com/repos/HippoCMMS/LoginSite/events',
            assignees_url: 'https://api.github.com/repos/HippoCMMS/LoginSite/assignees{/user}',
            branches_url: 'https://api.github.com/repos/HippoCMMS/LoginSite/branches{/branch}',
            tags_url: 'https://api.github.com/repos/HippoCMMS/LoginSite/tags',
            blobs_url: 'https://api.github.com/repos/HippoCMMS/LoginSite/git/blobs{/sha}',
            git_tags_url: 'https://api.github.com/repos/HippoCMMS/LoginSite/git/tags{/sha}',
            git_refs_url: 'https://api.github.com/repos/HippoCMMS/LoginSite/git/refs{/sha}',
            trees_url: 'https://api.github.com/repos/HippoCMMS/LoginSite/git/trees{/sha}',
            statuses_url: 'https://api.github.com/repos/HippoCMMS/LoginSite/statuses/{sha}',
            languages_url: 'https://api.github.com/repos/HippoCMMS/LoginSite/languages',
            stargazers_url: 'https://api.github.com/repos/HippoCMMS/LoginSite/stargazers',
            contributors_url: 'https://api.github.com/repos/HippoCMMS/LoginSite/contributors',
            subscribers_url: 'https://api.github.com/repos/HippoCMMS/LoginSite/subscribers',
            subscription_url: 'https://api.github.com/repos/HippoCMMS/LoginSite/subscription',
            commits_url: 'https://api.github.com/repos/HippoCMMS/LoginSite/commits{/sha}',
            git_commits_url: 'https://api.github.com/repos/HippoCMMS/LoginSite/git/commits{/sha}',
            comments_url: 'https://api.github.com/repos/HippoCMMS/LoginSite/comments{/number}',
            issue_comment_url: 'https://api.github.com/repos/HippoCMMS/LoginSite/issues/comments{/number}',
            contents_url: 'https://api.github.com/repos/HippoCMMS/LoginSite/contents/{+path}',
            compare_url: 'https://api.github.com/repos/HippoCMMS/LoginSite/compare/{base}...{head}',
            merges_url: 'https://api.github.com/repos/HippoCMMS/LoginSite/merges',
            archive_url: 'https://api.github.com/repos/HippoCMMS/LoginSite/{archive_format}{/ref}',
            downloads_url: 'https://api.github.com/repos/HippoCMMS/LoginSite/downloads',
            issues_url: 'https://api.github.com/repos/HippoCMMS/LoginSite/issues{/number}',
            pulls_url: 'https://api.github.com/repos/HippoCMMS/LoginSite/pulls{/number}',
            milestones_url: 'https://api.github.com/repos/HippoCMMS/LoginSite/milestones{/number}',
            notifications_url: 'https://api.github.com/repos/HippoCMMS/LoginSite/notifications{?since,all,participating}',
            labels_url: 'https://api.github.com/repos/HippoCMMS/LoginSite/labels{/name}',
            releases_url: 'https://api.github.com/repos/HippoCMMS/LoginSite/releases{/id}',
            deployments_url: 'https://api.github.com/repos/HippoCMMS/LoginSite/deployments',
            created_at: '2018-09-14T14:52:26Z',
            updated_at: '2018-10-05T20:21:54Z',
            pushed_at: '2018-10-06T21:56:36Z',
            git_url: 'git://github.com/HippoCMMS/LoginSite.git',
            ssh_url: 'git@github.com:HippoCMMS/LoginSite.git',
            clone_url: 'https://github.com/HippoCMMS/LoginSite.git',
            svn_url: 'https://github.com/HippoCMMS/LoginSite',
            homepage: null,
            size: 709,
            stargazers_count: 0,
            watchers_count: 0,
            language: 'JavaScript',
            has_issues: true,
            has_projects: true,
            has_downloads: true,
            has_wiki: true,
            has_pages: false,
            forks_count: 0,
            mirror_url: null,
            archived: false,
            open_issues_count: 2,
            license: null,
            forks: 0,
            open_issues: 2,
            watchers: 0,
            default_branch: 'master'
        }
    },
    _links:
    {
        self:
            { href: 'https://api.github.com/repos/HippoCMMS/LoginSite/pulls/10' },
        html: { href: 'https://github.com/HippoCMMS/LoginSite/pull/10' },
        issue:
            { href: 'https://api.github.com/repos/HippoCMMS/LoginSite/issues/10' },
        comments:
            { href: 'https://api.github.com/repos/HippoCMMS/LoginSite/issues/10/comments' },
        review_comments:
            { href: 'https://api.github.com/repos/HippoCMMS/LoginSite/pulls/10/comments' },
        review_comment:
            { href: 'https://api.github.com/repos/HippoCMMS/LoginSite/pulls/comments{/number}' },
        commits:
            { href: 'https://api.github.com/repos/HippoCMMS/LoginSite/pulls/10/commits' },
        statuses:
            { href: 'https://api.github.com/repos/HippoCMMS/LoginSite/statuses/5d3954c86ff2fe10efe769ad7f33a2724228f6d4' }
    },
    author_association: 'CONTRIBUTOR',
    merged: false,
    mergeable: true,
    rebaseable: true,
    mergeable_state: 'behind',
    merged_by: null,
    comments: 0,
    review_comments: 0,
    maintainer_can_modify: false,
    commits: 1,
    additions: 1,
    deletions: 0,
    changed_files: 1
}